<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class WebmailSettings extends Model
{
    protected $fillable = [
        'enabled',
        'subdomain',
        'port',
        'skin',
        'session_lifetime',
        'max_message_size',
        'spell_check_enabled',
        'plugins',
    ];

    protected $casts = [
        'enabled' => 'boolean',
        'port' => 'integer',
        'session_lifetime' => 'integer',
        'max_message_size' => 'integer',
        'spell_check_enabled' => 'boolean',
        'plugins' => 'array',
    ];

    public static function getSettings(): self
    {
        return self::firstOrCreate(
            ['id' => 1],
            [
                'enabled' => false,
                'subdomain' => 'webmail',
                'port' => 443,
                'skin' => 'elastic',
                'session_lifetime' => 30,
                'max_message_size' => 26214400,
                'spell_check_enabled' => true,
                'plugins' => ['archive', 'zipdownload', 'managesieve', 'password'],
            ]
        );
    }

    public function getAvailableSkins(): array
    {
        return [
            'elastic' => 'Elastic (Modern)',
            'larry' => 'Larry (Classic)',
        ];
    }

    public function getAvailablePlugins(): array
    {
        return [
            'archive' => 'Archive messages',
            'zipdownload' => 'Download attachments as ZIP',
            'managesieve' => 'Manage email filters',
            'password' => 'Change password',
            'markasjunk' => 'Mark as spam button',
            'newmail_notifier' => 'New mail notifications',
            'emoticons' => 'Emoticons support',
            'vcard_attachments' => 'vCard support',
            'additional_message_headers' => 'Additional headers',
            'attachment_reminder' => 'Attachment reminder',
        ];
    }

    public function generateConfig(): string
    {
        $config = "<?php\n\n";
        $config .= "// Roundcube Configuration - Generated by Laranode\n\n";

        $config .= "\$config['db_dsnw'] = 'mysql://roundcube:' . getenv('ROUNDCUBE_DB_PASSWORD') . '@localhost/roundcube';\n";
        $config .= "\$config['imap_host'] = 'localhost:143';\n";
        $config .= "\$config['smtp_host'] = 'localhost:587';\n";
        $config .= "\$config['smtp_user'] = '%u';\n";
        $config .= "\$config['smtp_pass'] = '%p';\n\n";

        $config .= "\$config['support_url'] = '';\n";
        $config .= "\$config['product_name'] = 'Webmail';\n";
        $config .= "\$config['skin'] = '{$this->skin}';\n\n";

        $config .= "\$config['session_lifetime'] = {$this->session_lifetime};\n";
        $config .= "\$config['max_message_size'] = '{$this->getMaxMessageSizeFormatted()}';\n\n";

        $config .= "\$config['spellcheck_engine'] = " . ($this->spell_check_enabled ? "'pspell'" : "null") . ";\n\n";

        $plugins = $this->plugins ?? [];
        $pluginList = implode("', '", $plugins);
        $config .= "\$config['plugins'] = ['{$pluginList}'];\n\n";

        // Security settings
        $config .= "// Security\n";
        $config .= "\$config['force_https'] = true;\n";
        $config .= "\$config['use_https'] = true;\n";
        $config .= "\$config['login_autocomplete'] = 0;\n";
        $config .= "\$config['ip_check'] = true;\n";
        $config .= "\$config['referer_check'] = true;\n\n";

        // Encryption
        $config .= "\$config['cipher_method'] = 'AES-256-CBC';\n";
        $config .= "\$config['des_key'] = '" . bin2hex(random_bytes(12)) . "';\n";

        return $config;
    }

    public function getMaxMessageSizeFormatted(): string
    {
        $mb = $this->max_message_size / 1048576;
        return $mb . 'M';
    }

    public function getWebmailUrl(string $domain): string
    {
        return "https://{$this->subdomain}.{$domain}";
    }
}
